export const REQUESTING_ARTICLE_DATAS = 'REQUESTING_ARTICLE_DATAS';
export const REQUEST_ARTICLE_DATA_FAILED = 'REQUEST_ARTICLE_DATA_FAILED';
export const REQUEST_ARTICLE_DATA_SUCCESS = 'REQUEST_ARTICLE_DATA_SUCCESS';

export const REQUESTING_BOOK_DATAS = 'REQUESTING_BOOK_DATAS';
export const REQUEST_BOOK_DATA_FAILED = 'REQUEST_BOOK_DATA_FAILED';
export const REQUEST_BOOK_DATA_SUCCESS = 'REQUEST_BOOK_DATA_SUCCESS';
